version: '3.5'
services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - pg16data:/var/lib/postgresql/data
    env_file:
      - ./.zabbix.env

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
    restart: always
    depends_on:
      - "db"
    env_file:
      - ./.zabbix.env

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
      - "127.0.0.1:7000:8080"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_SERVER_HOST: zabbix-server
    env_file:
      - ./.zabbix.env

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    ports:
      - "127.0.0.1:10050:10050"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_HOSTNAME: Zabbix server

volumes:
  pg16data:
